<?php echo $this->doctype('XHTML1_STRICT') . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<?php echo $this->headTitle() . "\n" ?>
<?php echo $this->headLink() . "\n" ?>
<?php echo $this->headScript() ?>
</head>
<body class="<?php echo $this->bodyClass ?>">
<?php echo $this->layout()->content . "\n" ?>
</body>
</html>