<!--
	 Copyright Netvibes 2006-2009.
	 This file is part of Exposition PHP Server.
	 
	 Exposition PHP Server is free software: you can redistribute it and/or modify
	 it under the terms of the GNU Lesser General Public License as published by
	 the Free Software Foundation, either version 3 of the License, or
	 (at your option) any later version.
	 
	 Exposition PHP Server is distributed in the hope that it will be useful,
	 but WITHOUT ANY WARRANTY; without even the implied warranty of
	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	 GNU Lesser General Public License for more details.
	 
	 You should have received a copy of the GNU Lesser General Public License
	 along with Exposition PHP Server. If not, see <http://www.gnu.org/licenses/>.
-->
<html>
<head>
<title>Exposition Widget Server</title>
</head>
<body>
<h1><?php echo $this->status ?></h1>
<?php echo $this->message ?>
<p>
<?php echo $this->details ?>
<hr>
<address>
widget server at <?php echo $this->host ?>
</address>
</body>
</html>